Require rspec/core in spec_helper.rb
The usage of this gem gives the following error when running on

Ruby 2.2.0
Rspec 3.3.2
Rails 4.2.3

```ruby
rake aborted!
NoMethodError: undefined method `configure' for RSpec:Module
/home/ubuntu/mailer-blaster/vendor/bundle/ruby/2.2.0/bundler/gems/rock_candy-5695c7b231a4/lib/rock_candy.rb:8:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb:76:in `require'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb:72:in `each'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb:72:in `block in require'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb:61:in `each'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler/runtime.rb:61:in `require'
/home/ubuntu/.rvm/gems/ruby-2.2.0@global/gems/bundler-1.9.5/lib/bundler.rb:134:in `require'
/home/ubuntu/mailer-blaster/config/application.rb:7:in `<top (required)>'
/home/ubuntu/mailer-blaster/Rakefile:4:in `require'
/home/ubuntu/mailer-blaster/Rakefile:4:in `<top (required)>'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'

- Explicitly require the `rspec/core` file before the `Rspec.configure`

```